# Generated by Django 5.2 on 2025-04-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegionalBoxOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("지역", models.CharField(max_length=5)),
                ("한국_상영편수", models.IntegerField()),
                ("한국_매출액", models.BigIntegerField()),
                ("한국_관객수", models.IntegerField()),
                ("한국_점유율", models.FloatField()),
                ("외국_상영편수", models.IntegerField()),
                ("외국_매출액", models.BigIntegerField()),
                ("외국_관객수", models.IntegerField()),
                ("외국_점유율", models.FloatField()),
                ("전체_상영편수", models.IntegerField()),
                ("전체_매출액", models.BigIntegerField()),
                ("전체_관객수", models.IntegerField()),
                ("전체_점유율", models.FloatField()),
                ("기준_시작일", models.DateField()),
                ("기준_종료일", models.DateField()),
            ],
            options={
                "verbose_name": "지역별 박스오피스",
                "verbose_name_plural": "지역별 박스오피스",
            },
        ),
    ]
