# Generated by Django 5.2 on 2025-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalBoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('title', models.CharField(max_length=255, verbose_name='영화제목')),
                ('release_date', models.DateField(verbose_name='개봉일')),
                ('weekend_revenue', models.FloatField(verbose_name='주말매출액')),
                ('weekend_revenue_currency', models.CharField(choices=[('$', 'USD'), ('£', 'GBP'), ('€', 'EUR'), ('¥', 'JPY')], default='$', max_length=1, verbose_name='주말매출액 통화')),
                ('total_revenue', models.FloatField(verbose_name='누적매출액')),
                ('total_revenue_currency', models.CharField(choices=[('$', 'USD'), ('£', 'GBP'), ('€', 'EUR'), ('¥', 'JPY')], default='$', max_length=1, verbose_name='누적매출액 통화')),
                ('distributor', models.CharField(max_length=255, verbose_name='배급사')),
                ('country', models.CharField(choices=[('US', '미국'), ('UK', '영국'), ('DE', '독일'), ('JP', '일본')], max_length=2, verbose_name='국가')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('week', models.IntegerField(verbose_name='주차')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '해외 박스오피스',
                'verbose_name_plural': '해외 박스오피스',
                'db_table': 'international_boxoffice',
                'indexes': [models.Index(fields=['country', 'year', 'week'], name='internation_country_29c2aa_idx'), models.Index(fields=['title'], name='internation_title_1f2f7b_idx')],
                'unique_together': {('country', 'year', 'week', 'title')},
            },
        ),
    ]
