# Generated by Django 5.2 on 2025-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie10days",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=255)),
                ("days_since_release", models.CharField(max_length=50)),
                ("screen_num", models.IntegerField()),
                ("screenings_num", models.IntegerField()),
                ("revenue", models.IntegerField()),
                ("moviegoers_num", models.IntegerField()),
                ("revenue_cumulative", models.IntegerField()),
                ("moviegoers_cumulative", models.IntegerField()),
                ("rank", models.CharField(max_length=10)),
            ],
        ),
    ]
