version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Applying migrations...
      - python manage.py makemigrations
      - python manage.py migrate
      - echo Collecting static files...
      - python manage.py collectstatic --noinput

  build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'      # 전체 파일을 다 포함시킴
  discard-paths: no  # 디렉토리 구조를 유지함
