# Generated by Django 5.2 on 2025-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255, verbose_name='영화명')),
                ('release_date', models.CharField(max_length=20, verbose_name='개봉일')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('is_now_showing', models.BooleanField(default=False, verbose_name='현재 상영 여부')),
                ('country', models.CharField(max_length=30, verbose_name='국가')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='연도별 순위')),
                ('movie_name', models.CharField(max_length=255, verbose_name='영화명')),
                ('release_date', models.CharField(max_length=20, verbose_name='개봉일')),
                ('sales', models.CharField(max_length=30, verbose_name='누적판매액')),
                ('audience', models.CharField(max_length=30, verbose_name='누적관객수')),
                ('screen', models.CharField(max_length=20, verbose_name='스크린수')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
            ],
        ),
    ]
